grocsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp1.urls')),
]

myapp1/urls.py
from django.urls import path
from . import views
app_name = 'myapp1'
urlpatterns = [
    path('', views.index, name='index'),
    path('myapp1/about/', views.about, name='about'),
    path('myapp1/<int:type_no>/', views.detail, name='detail'),
    path('myapp1/items', views.items, name='item'),
    path('myapp1/items/<int:item_id>/', views.itemdetail, name='item'),
    path('myapp1/placeorder', views.placeorder, name='placeorder'),

]

myapp1/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone


class Type(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Item(models.Model):
    type = models.ForeignKey(Type, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100)
    available = models.BooleanField(default=True)
    desc = models.TextField(blank=True, null=True)
    interested = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "name: {0}, type: {1}, price: {2}, stock: {3}".format(self.name, self.type, self.price, self.stock)

    def topup(self):
        self.stock += 200

class Client(User):
    CITY_CHOICES = [('WD', 'Windsor'), ('TO', 'Toronto'), ('CH', 'Chatham'), ('WL', 'WATERLOO')]
    # fullname = models.CharField(max_length=50)
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='CH')
    interested_in = models.ManyToManyField(Type)
    phone = models.CharField(max_length=12, null=True, blank=True)

    def __str__(self):
        return "username: {0}, Address: {1}, City: {2}".format(self.username, self.shipping_address, self.city)


class OrderItem(models.Model):
    item = models.ForeignKey(Item, related_name='OrderItems', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    qty_ordered = models.IntegerField()
    STATUS_CHOICES = [(0, 'Cancelled'), (1, 'Placed'), (2, 'Shipped'), (3, 'Delivered')]
    status = models.IntegerField(choices=STATUS_CHOICES, default='1')
    date = models.DateField(null=True, blank=True)

    def total_price(self):
        return self.qty_ordered * Item.objects.get(self.item).price

    def __str__(self):
        return "username: {0}, Item: {1}, Qty: {2}, Status: {3}".format(self.client.username, self.item, self.qty_ordered, self.status)

myapp1/forms.py
from django import forms
from myapp1.models import OrderItem


class OrderItemForm(forms.ModelForm):

    class Meta:
        model = OrderItem
        fields = ['item', 'client', 'qty_ordered']
        widgets = {
            'client': forms.RadioSelect,
        }

        labels = {
            'qty_ordered': 'Quantity',
            'client': 'Client Name'
        }


class InterestForm(forms.Form):
    # choices = (('Yes', 1), ('No', 0))
    choices = ((1, 'Yes'), (0, 'No'))
    interested = forms.ChoiceField(choices=choices, label='Are you Interested?', help_text='', widget=forms.RadioSelect)
    quantity = forms.IntegerField(min_value=1)
    comments = forms.CharField(label='Additional Comments', widget=forms.Textarea())

myapp1/views.py
from django.http import HttpResponse
from .models import Type, Item
from django.shortcuts import get_object_or_404, render
from .forms import InterestForm, OrderItemForm, OrderItem

# Create your views here.
# def index(request):
#     type_list = Item.objects.all().order_by('-price')[:7]
#     response = HttpResponse()
#     heading1 = '<p>' + 'Different Types: ' + '</p>'
#     response.write(heading1)
#     for type in type_list:
#         para = '<p>' + str(type.id) + ': ' + str(type) + '</p>'
#         response.write(para)
#     return response

def index(request):
    type_list = Type.objects.all().order_by('id')[:7]
    return render(request, 'myapp1/index0.html', {'type_list': type_list})


def about(request):
    # return HttpResponse("This is an Online Grocery Store")
    return render(request, 'myapp1/about0.html')


def detail(request, type_no):
    type_by_id = get_object_or_404(Type, id=type_no)
    item_by_type = Item.objects.filter(type_id=type_no)
    # response = HttpResponse()
    para = '<p>' + str(type_by_id.id) + ': ' + str(type_by_id.name) + '</p>'
    # response.write(para)
    # return response
    return render(request, 'myapp1/detail0.html', {'type': type_by_id, 'items': item_by_type})


def items(request):
    itemlist = Item.objects.all().order_by('id')[:20]
    return render(request, 'myapp1/items.html', {'itemlist': itemlist})

def itemdetail(request, item_id):
    try:
        item_by_id = Item.objects.get(id=item_id)
        if request.POST:
            form = InterestForm(request.POST)
            if form.is_valid():
                print("In interest form")
                interested = form.cleaned_data["interested"]
                print(interested)
                quantity = form.cleaned_data["quantity"]
                print(quantity)
                comments = form.cleaned_data["comments"]
                print(comments)
                i = item_by_id.interested + int(interested)
                item_by_id.interested = i
                print(item_by_id)
                item_by_id.save()
        form = InterestForm()
        return render(request, 'myapp1/itemdetail.html', {'item': item_by_id, 'form': form})
    except:
        context = {'msg': "Item with Item id " + str(item_id) + " does not exist!"}
        return render(request, 'myapp1/itemdetail.html', context)




def placeorder(request):
    msg = ''
    itemlist = Item.objects.all()
    orderitem = OrderItem.objects.all()[0]
    print(orderitem)
    if request.method == 'POST':
        form = OrderItemForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            print(str(order))
            if order.qty_ordered <= order.item.stock:
                print(str(order))
                item = Item.objects.get(id=order.item.id)
                updated_stock = item.stock - order.qty_ordered
                item.stock = updated_stock
                item.save(force_update=True)
                order.save()
                msg = 'Your order has been placed successfully.'
            else:
                msg = 'We do not have sufficient stock to fill your order.'
                print(msg)
                return render(request, 'myapp1/order_response.html', {'msg': msg})
    else:
        form = OrderItemForm()
    return render(request, 'myapp1/placeorder.html', {'form': form, 'msg': msg, 'itemlist': itemlist})

myapp1/templates/myapp1/about0.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head lang="en">#}
{#<meta charset="UTF-8">#}
{#<title> Online Grocery Store </title>#}
{#</head>#}
{#<body>#}
{#This is an Online Grocery Store#}
{#<p><a href={% url 'myapp1:index' %}>Main</a></p>#}
{#<p><a href="/">Main</a></p>#}
{#</body>#}
{#</html>#}

{% extends 'myapp1/base.html' %}

{% block body_block %}
    This is an Online Grocery Store
{#<p><a href={% url 'myapp1:index' %}>Main</a></p>#}
{% endblock %}

myapp1/templates/myapp1/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp1/style.css' %}"/>
    <title> Online Grocery Store - {% block title %} Welcome! {% endblock %}</title>
</head>
<body>
<div>
    <h1>{% block myhdg %} Hello from Group-1 {% endblock %}</h1>
    <h2> Welcome to Groscite, your own online Grocery Store</h2>
    {% block body_block %}*** {% endblock %}
</div>
<hr />
<div>
    <ul>
        <li class="hbar1"><a href="http://127.0.0.1:8000/myapp1/about/"> Find out about this site </a></li>
        <li class="hbar1"><a href = "{% url 'myapp1:index'%}"> Click here to return to main page </a><br/></li>
        <li class="hbar1"><a href = "{% url 'myapp1:item'%}"> Click here to see items </a><br/></li>
    </ul>
</div>
</body>

myapp1/templates/myapp1/detail0.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head lang="en">#}
{#<meta charset="UTF-8">#}
{#<title> Online Grocery Store </title>#}
{#</head>#}
{##}
{#<body>#}
{#The type for type no: {{ type.id }} is {{type.name}}#}
{#<br/>#}
{#<br/>#}
{#The type {{ type.name }} contains following items:#}
{##}
{#{% for i in items %}#}
{#        <li> {{ i.name}} </li>#}
{#        {% endfor %}#}
{#<p><a href={% url 'myapp1:index' %}>Main Page</a></p>#}
{##}
{#</body>#}
{#</html>#}

{% extends 'myapp1/base.html' %}

{% block body_block %}

    The type for type no: {{ type.id }} is {{type.name}}
<br/>
<br/>
The type {{ type.name }} contains following items:

{% for i in items %}
        <li> {{ i.name}} </li>
        {% endfor %}
{#<p><a href={% url 'myapp1:index' %}>Main Page</a></p>#}
{% endblock %}

myapp1/templates/myapp1/index0.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head lang="en">#}
{#<meta charset="UTF-8">#}
{#<title> Online Grocery Store </title>#}
{#</head>#}
{##}
{#<body>#}
{##}
{##}
{#</body>#}
{#</html>#}

{% extends 'myapp1/base.html' %}

{% block body_block %}
    {% if type_list %}
    <h2> List of Types </h2>
    <ol>
        {% for type in type_list %}
{#            <p><a href={% url 'myapp1:detail' parameter= type.id|floatformat:"0" %}>{{ type.name}}</a></p>#}
            <p><a href="/myapp1/{{type.id|floatformat:"0"}}">{{ type.name}}</a></p>
        {% endfor %}
    </ol>
{% else %}
<strong> None of the types is available! </strong>
{% endif %}
{#<p><a href={% url 'myapp1:about' %}>About Page</a></p>#}

{% endblock %}

myapp1/templates/myapp1/itemdetail.html
{% extends 'myapp1/base.html' %}

{% block body_block %}

<br/>
<br/>

    {%if msg %}
        {{ msg }}

    {% else %}
{#        {% for i in item %}#}
    You selected Item with Id {{ item.id }}
    <br/>
    Item: {{ item.name }}
    <br/>
    Interested: {{ item.interested }}
    <br/>
    Price: {{ item.price }}
{#        {% endfor %}#}
    {% endif %}

<div class="container">
    <form method="POST">
      <fieldset>
        <legend>Form</legend>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </fieldset>
    </form>
</div>
{% endblock %}

myapp1/templates/myapp1/items.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for item in itemlist %}
        <ul>
            <li> <a href="/myapp1/items/{{item.id|floatformat:"0"}}"> {{ item }} </a> </li>
        </ul>
    {% endfor %}
    <a href = {% url 'myapp1:placeorder' %}>Place Order</a>
</body>
</html>

myapp1/templates/myapp1/order_response.html
{% extends 'myapp1/base.html' %}

{% block body_block %}

<br/>
<br/>


        {{ msg }}


{% endblock %}

myapp1/templates/myapp1/placeorder.html
{% extends 'myapp1/base.html' %}

{% block body_block %}

<br/>

<div class="container">
    <form method="POST">
      <fieldset>
        <legend>Form</legend>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </fieldset>
    </form>
</div>
{% endblock %}